### PR TITLE
Adding Full ZZ-C (OLS)

### PR DESCRIPTION
**Pull request by soncScoot**
I may have messed it up as I was kinda brain-dead while doing this.  
Algorithms taken from here:
https://drive.google.com/file/d/0B4wnDYRRloa1Mmswb1JmZW8yV2s/view

### CODE REVIEW

**Comment by tao-yu** [comment]
Hi there. Thanks for the pull request, ZZ-C is something I definitely wanted to add to my trainer, but never did because of the difficulty of scraping algs from a pdf file. 

I checked some algs and I was unfortunately able to find some mistakes. Case 14, for example, has a wrong alg. 

With ZZ-C having so many algs I will have to insist on having proof that all the algs are correct. 

I think, practically speaking, a minimum acceptable level of proof is to create a spreadsheet with pictures showing what case each alg and each alternative alg solves, and fixing all the mistakes so that it matches the original pdf sheet. This of course assumes that the original pdf sheet is completely correct, which I think is reasonable enough. 

I should be able to write a Python script to do this pretty easily - unless you would like to try this first? Let me know what you think.

**Comment by soncScoot** [comment]
My knowledge of programming is rather limited, I entered all the algs manually by copying and pasting lol.  It would be greatly appreciated if you could write the script.

One thing to note about the PDF is for some reason it has the naming of the amount of corners oriented reversed from what it should be

Thanks for your help!

**Comment by tao-yu** [comment]
Alright, no worries, will try and get that working in a few days. From my testing, most of the algs were correct so hopefully it's just a few that need to be fixed. 

Good spot about the PDF, I guess "misoriented corners" was probably the intention. I don't think I will change anything as a result of this, I think the way you have organized the algs into sets is quite good. 

Thanks again for doing this, you've definitely done the bulk of the work here 👍

**Comment by soncScoot** [comment]
Sorry to spam you again, but I should have mentioned this earlier.  I forgot to mention that the algs I put in the list aren't necessarily 100% in order compared to the PDF.  I put the algs in order in each of the cases by number of corners oriented (4, 3, 2, 1, 0).  For example, with OLS cases 3 and 20 I manually ordered the cases based on the numbers of corners oriented rather than what's straight down the document.  

[Here's what I have on my modified version of your trainer w/ OLS cases divided by the number of corners oriented, might help you better understand what I'm talking about.](https://github.com/soncScoot/soncscoot.github.io/blob/master/js/alg_list.js)

**Comment by tao-yu** [comment]
Alright, I have finally finished manually checking through and fixing all issues in the algs.

For reference, the sheet I created to check the algs is here (the algs are corrected in this version): https://bit.ly/385Wlcw

Summary of changes made
- Several algs were incorrect in the original sheet and thus were also wrong when copied over - I fixed these.
- An alg was missing from case 11
- Case 5 (aka Winter Variation) had quite a few typos and and was missing one alg. I replaced the algs in this set with the algs from the "WVLS (FR)" set which was already on my trainer. This is for simplicity and also for consistency.
- The name "OLS" was changed to "ZZ OLS (Egide Hirwa)"
- I added better algs for a small few cases where I happened to know one (mostly cases which could be solved using a commutator). 

If you encounter any more problems, please let me know. 

Thanks again for your work! Proud to now have the first and only ZZ OLS trainer that I know of, and it would not have been possible without your contribution :)

**Pull request merged**
